export const ADD_CATEGORY='ADD_CATEGORY';
export const ADD_CATEGORY_IN='ADD_CATEGORY_IN';
export const ADD_CATEGORY_SUCCESS='ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_ERR='ADD_CATEGORY_ERR';


export const DELETE_CATEGORY='DELETE_CATEGORY';
export const DELETE_CATEGORY_IN='DELETE_CATEGORY_IN';
export const DELETE_CATEGORY_SUCCESS='DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERR='DELETE_CATEGORY_ERR';


export const UPDATE_CATEGORY='UPDATE_CATEGORY';
export const UPDATE_CATEGORY_IN='UPDATE_CATEGORY_IN';
export const UPDATE_CATEGORY_SUCCESS='UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_ERR='UPDATE_CATEGORY_ERR';


export const resetCategory='resetCategory';